main: me.kakalavala.linkedchests.core.Core
name: LinkedChests
version: 1.0
api-version: 1.13
author: Kakalavala
description: A Minecraft 1.13 Plugin that links chests together.

commands:
  givechestlinker:
    description: Gives the player a ChestLinker.
    aliases: [givelinker, gcl]